# Generated by Django 5.1 on 2024-09-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0003_framework_varity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework_varity',
            name='documentation_url',
            field=models.URLField(blank=True),
        ),
    ]
