# Generated by Django 5.1 on 2024-09-07 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0004_framework_varity_documentation_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework_varity',
            name='framework_type',
            field=models.CharField(choices=[('React', 'JavaScript'), ('Next.js', 'TypeScript'), ('Django', 'Python'), ('Angular.js', 'TypeScript')], default='React', max_length=50),
        ),
        migrations.CreateModel(
            name='FrameWork_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=50)),
                ('certificate_number', models.CharField(max_length=50)),
                ('certificate_description', models.TextField(default='')),
                ('certificate_image', models.ImageField(upload_to='djangoApp/images')),
                ('certificate_url', models.URLField(blank=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.framework_varity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Framework_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_description', models.TextField(default='')),
                ('course_duration', models.CharField(max_length=50)),
                ('course_price', models.CharField(max_length=50)),
                ('course_image', models.ImageField(upload_to='djangoApp/images')),
                ('course_url', models.URLField(blank=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.framework_varity')),
            ],
        ),
        migrations.CreateModel(
            name='Framework_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(default='')),
                ('rating', models.IntegerField(default=0)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.framework_varity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
